### ISSUE TITLE
Generar conversaciones de el jugador hacia un npc

### ISSUE THREAD

**Issue by o-hgm** [o-hgm/jam-session-video-game#5]
# Descripción general
Para desarrollar la parte conversacional queremos tener un conjunto de conversaciones entre el jugador principal y un npc.
Estas conversaciones no serán lineales, ramificando las opciones e indicando lo que ocurre como consecuencia de estas. Un ejemplo sería:

```yaml
- node_id: 1
  message: "Hola, bienvenido a nuestro hotel. ¿En qué puedo ayudarte hoy?"
  choices:
    choice_1:
      message: "Me gustaría quejarme de la limpieza de mi habitación. No está bien."
      action_to_perform:
        - move_to: 2
    choice_2:
      message: "Me encanta este hotel. Todo está muy limpio y organizado."
      action_to_perform:
        - move_to: 3
        - actions:
            - increase_self_esteem:
              - value: 1

- node_id: 2
  message: "Lamento escuchar eso. ¿Puedes decirme más sobre el problema?"
  choices:
    choice_1:
      message: "Mi habitación no se limpió adecuadamente y todavía hay basura en el piso."
      action_to_perform:
        - move_to: 4
        - actions:
            - reduce_self_esteem:
              - value: 1

- node_id: 3
  message: "¡Gracias por tus amables palabras! Nos esforzamos mucho para mantener todo limpio y ordenado aquí en nuestro hotel."
  
- node_id: 4
  message: "Lo siento mucho por las molestias. Hablaré con nuestro personal de limpieza para asegurarme de que se tomen medidas y se solucione el problema lo antes posible." 

```

# Tareas  
+ [ ] Utilizar chatgpt para, a partir de las conversaciones generadas previamente y publicadas en discord crear estructuras similares a la comentada al inicio para facilitar su integración en el juego.
 
# Criterio de Aceptación
Esta tarea está terminada cuando, en la carpeta resources se incluya una conversación de ejemplo (i.e `resources/conversations/example_make_your_npc_angry.yaml`

**Comment by o-hgm** [comment]
En chatgpt he utilizado el siguiente prompt para generar la conversación de ejemplo:

```
- node_id: 1
    - message: "Eres un hijo de puta"
    - choices:
        choice_1:
            - message: "Tienes razón"
            - action_to_perform:
                - move_to: 2
        choice_2:
            - message: "Te Mato"
            - action_to_perform:
                - move_to: 4

- node_id: 2
    - actions:
        - reduce_motivation:
            - value: 1

- node_id: 4
    - actions:
        - increase_anger:
            - value: 1


Esto es un ejemplo en yaml para un juego conversacional. Escribe un ejemplo en el que el jugador hace un comentario sobre el trabajo del npc.
```

Posteriormente le he aclarado:

```
los nodos pueden tener acciones. En este ejemplo, el nodo 3 aumentaria la autoestima del npc y el nodo 4 la reduciría. Actualiza el ejemplo para representar esto.
```
